[package]
name = "lumina"
version = "0.1.0"
description = "A Steam-free Linux launcher experience for Zenless Zone Zero"
authors = ["Lumina contributors"]
edition = "2021"
license = "MIT"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = [] }
